server:
  port: 443
#  ssl:
#    key-store: classpath:www.liangbao.cn.jks
#    key-store-type: JKS
#    key-store-password: 3t9s4iyq

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vote?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Liaowei123@
#    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  jackson:
    # 格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: cn.lsnu.vote.model.domain
  configuration:
    call-setters-on-nulls: false  # 关闭查询结果为null无法返回
    map-underscore-to-camel-case: true  # 开启驼峰命名规则
    auto-mapping-behavior: full # 自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml




