server:
  port: 9090
#  port: 4270
  ssl:
    key-store: classpath:ls.0833h.cn.jks
    key-store-type: JKS
    key-store-password: n0907ks2i2
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vote?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Liaowei123@
#    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 3
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000 # 超时链接 单位ms
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池分配连接最大阻塞等待时间（阻塞时间到，抛出异常。使用负值表示无限期阻塞）
        max-idle: 8 # 连接池中的最大空闲连接数
        min-idle: 0 # 连接池中的最小空闲连接数


  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  jackson:
    # 格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: cn.lsnu.vote.model.domain
  configuration:
    call-setters-on-nulls: false  # 关闭查询结果为null无法返回
    map-underscore-to-camel-case: true  # 开启驼峰命名规则
    auto-mapping-behavior: full # 自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

app:
  appid: wxda9bed06c4087d2e
  secret: 91933c3a22369f8f1fb6ade8fb66e160



